enableScripts: false
nmMode: hardlinks-global
nodeLinker: node-modules
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@oxfmt/binding-*@0.46.0'
  - '@oxlint/binding-*@1.61.0'
  - '@voidzero-dev/vite-plus-*@0.1.19'
  - oxfmt@0.46.0
  - oxlint@1.61.0
  - vite-plus@0.1.19

packageExtensions:
  '@types/webpack-node-externals@*':
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
  webpack-node-externals@*:
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
