enableScripts: false
nmMode: hardlinks-global
nodeLinker: node-modules

packageExtensions:
  '@types/webpack-node-externals@*':
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
  webpack-node-externals@*:
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
