enableScripts: false
nmMode: hardlinks-global
nodeLinker: node-modules
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@oxfmt/binding-*@0.43.0'
  - '@oxlint/binding-*@1.58.0'
  - '@voidzero-dev/vite-plus-*@0.1.15'
  - oxfmt@0.43.0
  - oxlint@1.58.0
  - vite-plus@0.1.15

packageExtensions:
  '@types/webpack-node-externals@*':
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
  webpack-node-externals@*:
    peerDependencies:
      webpack: ^5
    peerDependenciesMeta:
      webpack:
        optional: true
