packages:
  - packages/*
  - examples/elasticsearch/*
  - examples/hatchet/*
  - examples/webpack/*

publicHoistPattern:
  - '*commitlint*'
  - '*eslint*'
  - '*postcss*'
  - '*prettier*'
  - '*stylelint*'
  - lint-staged
  - sort-package-json
