packages:
  - packages/*
  - examples/elasticsearch/*
  - examples/hatchet/*
  - examples/node/*
  - examples/react/*
  - examples/tanstack/*
  - examples/temporal/*
  - examples/typescript/*
  - examples/webpack/*
  - stories

patchedDependencies:
  vite-plugin-solid@2.11.10: patches/vite-plugin-solid@2.11.10.patch

publicHoistPattern:
  - '*commitlint*'
  - '*eslint*'
  - '*postcss*'
  - '*prettier*'
  - '*stylelint*'
  - '*tailwind*'
  - lint-staged
  - oxlint
  - sort-package-json

dangerouslyAllowAllBuilds: true
