minimumReleaseAge: 4320
nodeLinker: hoisted
autoInstallPeers: false

packages:
  - examples/elasticsearch/*
  - examples/grafana/*
  - examples/hatchet/*
  - examples/http/*
  - examples/node/*
  - examples/react-server/*
  - examples/tanstack/*
  - examples/temporal/*
  - examples/typescript/*
  - examples/webpack/*
  - packages/*
  - stories

patchedDependencies:
  vite-plugin-solid@2.11.11: patches/vite-plugin-solid@2.11.11.patch

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-*'
  - vite-plus@1.1.0

allowBuilds:
  '@hatchet-dev/typescript-sdk': false
  '@swc/core': false
  '@temporalio/core-bridge': false
  bcrypt: false
  esbuild: false
  protobufjs: false
  unrs-resolver: false
