sonar.organization=yjoer
sonar.projectKey=yjoer_camp

sonar.issue.ignore.multicriteria=py_s905

# non-empty-statements
sonar.issue.ignore.multicriteria.py_s905.ruleKey=python:S905
sonar.issue.ignore.multicriteria.py_s905.resourceKey=notebooks/**/*
