sonar.organization=yjoer
sonar.projectKey=yjoer_camp

sonar.issue.ignore.multicriteria=java_s116,\
	java_s117,\
	py_s905

# field-names
sonar.issue.ignore.multicriteria.java_s116.ruleKey=java:S116
sonar.issue.ignore.multicriteria.java_s116.resourceKey=**/*

# variable-names
sonar.issue.ignore.multicriteria.java_s117.ruleKey=java:S117
sonar.issue.ignore.multicriteria.java_s117.resourceKey=**/*

# non-empty-statements
sonar.issue.ignore.multicriteria.py_s905.ruleKey=python:S905
sonar.issue.ignore.multicriteria.py_s905.resourceKey=notebooks/**/*
