sonar.organization=yjoer
sonar.projectKey=yjoer_camp

sonar.issue.ignore.multicriteria=cpp_s1117,\
	cpp_s5421,\
	java_s100,\
	java_s106,\
	java_s116,\
	java_s117,\
	py_s905,\
	ts_s7503

# variable-shadowing
sonar.issue.ignore.multicriteria.cpp_s1117.ruleKey=cpp:S1117
sonar.issue.ignore.multicriteria.cpp_s1117.resourceKey=notebooks/**/*

# global-variables
sonar.issue.ignore.multicriteria.cpp_s5421.ruleKey=cpp:S5421
sonar.issue.ignore.multicriteria.cpp_s5421.resourceKey=notebooks/**/*

# method-names
sonar.issue.ignore.multicriteria.java_s100.ruleKey=java:S100
sonar.issue.ignore.multicriteria.java_s100.resourceKey=**/*

# standard-outputs
sonar.issue.ignore.multicriteria.java_s106.ruleKey=java:S106
sonar.issue.ignore.multicriteria.java_s106.resourceKey=notebooks/**/*

# field-names
sonar.issue.ignore.multicriteria.java_s116.ruleKey=java:S116
sonar.issue.ignore.multicriteria.java_s116.resourceKey=**/*

# variable-names
sonar.issue.ignore.multicriteria.java_s117.ruleKey=java:S117
sonar.issue.ignore.multicriteria.java_s117.resourceKey=**/*

# non-empty-statements
sonar.issue.ignore.multicriteria.py_s905.ruleKey=python:S905
sonar.issue.ignore.multicriteria.py_s905.resourceKey=notebooks/**/*

# typescript/require-await
sonar.issue.ignore.multicriteria.ts_s7503.ruleKey=typescript:S7503
sonar.issue.ignore.multicriteria.ts_s7503.resourceKey=**/*
