[workspace]
channels = ["conda-forge"]
name = "cuda-basics"
platforms = ["win-64"]
version = "2025.7.0"

[tasks.configure]
cmd = [
  "cmake",
  "-G",
  "Ninja",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DCMAKE_C_COMPILER_LAUNCHER=ccache",
  "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
  "-S",
  ".",
  "-B",
  ".build",
]

[tasks.build]
cmd = ["ninja", "-C", ".build"]
depends-on = ["configure"]

[tasks.start]
cmd = "./.build/cuda-basics"
