import { defineConfig } from 'oxlint';

export const oxlint_config = defineConfig({
	plugins: ['import', 'jsx-a11y', 'react', 'unicorn'],
	categories: {
		correctness: 'error',
	},
	rules: {
		'import/default': 'off',
		'import/named': 'error',
		'import/no-duplicates': 'warn',
		'import/no-named-as-default': 'warn',
		'import/no-named-as-default-member': 'warn',
		'import/no-named-default': 'error', // unicorn recommended
		'react/display-name': 'error',
		'react/jsx-no-comment-textnodes': 'error',
		'react/jsx-no-target-blank': 'error',
		'react/no-unescaped-entities': 'error',
		'react/no-unknown-property': ['error', { ignore: ['class', 'sx'], requireDataLowercase: true }],
		'react/no-unsafe': 'error',
		'react/require-render-return': 'error', // nursery
		'unicorn/catch-error-name': 'error',
		'unicorn/consistent-assert': 'error',
		'unicorn/consistent-date-clone': 'error',
		'unicorn/consistent-empty-array-spread': 'error',
		'unicorn/consistent-existence-index-check': 'error',
		'unicorn/consistent-function-scoping': 'error',
		'unicorn/empty-brace-spaces': 'error',
		'unicorn/error-message': 'error',
		'unicorn/escape-case': 'error',
		'unicorn/explicit-length-check': 'error',
		'unicorn/filename-case': ['error', { cases: { kebabCase: true } }],
		'unicorn/new-for-builtins': 'error',
		'unicorn/no-abusive-eslint-disable': 'error',
		'unicorn/no-accessor-recursion': 'error',
		'unicorn/no-anonymous-default-export': 'error',
		'unicorn/no-array-callback-reference': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-array-method-this-argument': 'error',
		'unicorn/no-array-reduce': 'error',
		'unicorn/no-array-reverse': 'off',
		'unicorn/no-array-sort': 'off',
		'unicorn/no-await-expression-member': 'error',
		'unicorn/no-await-in-promise-methods': 'error',
		'unicorn/no-console-spaces': 'error',
		'unicorn/no-document-cookie': 'error',
		'unicorn/no-hex-escape': 'error',
		'unicorn/no-immediate-mutation': 'error',
		'unicorn/no-instanceof-builtins': 'error',
		'unicorn/no-lonely-if': 'error',
		'unicorn/no-magic-array-flat-depth': 'error',
		'unicorn/no-negation-in-equality-check': 'error',
		'unicorn/no-nested-ternary': 'error',
		'unicorn/no-new-buffer': 'error',
		'unicorn/no-null': 'error',
		'unicorn/no-object-as-default-parameter': 'error',
		'unicorn/no-process-exit': 'error',
		'unicorn/no-static-only-class': 'error',
		'unicorn/no-this-assignment': 'error',
		'unicorn/no-typeof-undefined': 'error',
		'unicorn/no-unnecessary-array-flat-depth': 'error',
		'unicorn/no-unnecessary-array-splice-count': 'error',
		'unicorn/no-unnecessary-slice-end': 'error',
		'unicorn/no-unreadable-array-destructuring': 'error',
		'unicorn/no-unreadable-iife': 'error',
		'unicorn/no-useless-collection-argument': 'error',
		'unicorn/no-useless-error-capture-stack-trace': 'error',
		'unicorn/no-useless-fallback-in-spread': 'error',
		'unicorn/no-useless-length-check': 'error',
		'unicorn/no-useless-promise-resolve-reject': 'error',
		'unicorn/no-useless-switch-case': 'error',
		'unicorn/no-useless-undefined': 'error',
		'unicorn/no-zero-fractions': 'error',
		'unicorn/number-literal-case': 'error',
		'unicorn/numeric-separators-style': 'error',
		'unicorn/prefer-add-event-listener': 'error',
		'unicorn/prefer-array-find': 'error',
		'unicorn/prefer-array-flat': 'error',
		'unicorn/prefer-array-flat-map': 'error',
		'unicorn/prefer-array-index-of': 'error',
		'unicorn/prefer-array-some': 'error',
		'unicorn/prefer-at': 'error',
		'unicorn/prefer-bigint-literals': 'error',
		'unicorn/prefer-blob-reading-methods': 'error',
		'unicorn/prefer-class-fields': 'error',
		'unicorn/prefer-classlist-toggle': 'error',
		'unicorn/prefer-code-point': 'error',
		'unicorn/prefer-date-now': 'error',
		'unicorn/prefer-default-parameters': 'error',
		'unicorn/prefer-dom-node-append': 'error',
		'unicorn/prefer-dom-node-dataset': 'error',
		'unicorn/prefer-dom-node-remove': 'error',
		'unicorn/prefer-dom-node-text-content': 'error',
		'unicorn/prefer-event-target': 'error',
		'unicorn/prefer-global-this': 'error',
		'unicorn/prefer-includes': 'error',
		'unicorn/prefer-keyboard-event-key': 'error',
		'unicorn/prefer-logical-operator-over-ternary': 'error',
		'unicorn/prefer-math-min-max': 'error',
		'unicorn/prefer-math-trunc': 'error',
		'unicorn/prefer-modern-dom-apis': 'error',
		'unicorn/prefer-modern-math-apis': 'error',
		'unicorn/prefer-module': 'error',
		'unicorn/prefer-native-coercion-functions': 'error',
		'unicorn/prefer-negative-index': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/prefer-number-properties': 'error',
		'unicorn/prefer-object-from-entries': 'error',
		'unicorn/prefer-optional-catch-binding': 'error',
		'unicorn/prefer-prototype-methods': 'error',
		'unicorn/prefer-query-selector': 'error',
		'unicorn/prefer-reflect-apply': 'error',
		'unicorn/prefer-regexp-test': 'error',
		'unicorn/prefer-response-static-json': 'error',
		'unicorn/prefer-set-has': 'error',
		'unicorn/prefer-spread': 'error',
		'unicorn/prefer-string-raw': 'error',
		'unicorn/prefer-string-replace-all': 'error',
		'unicorn/prefer-string-slice': 'error',
		'unicorn/prefer-string-trim-start-end': 'error',
		'unicorn/prefer-structured-clone': 'error',
		'unicorn/prefer-ternary': 'off',
		'unicorn/prefer-top-level-await': 'error',
		'unicorn/prefer-type-error': 'error',
		'unicorn/relative-url-style': 'error',
		'unicorn/require-array-join-separator': 'error',
		'unicorn/require-module-attributes': 'error',
		'unicorn/require-module-specifiers': 'error',
		'unicorn/require-number-to-fixed-digits-argument': 'error',
		'unicorn/switch-case-braces': 'error',
		'unicorn/text-encoding-identifier-case': 'error',
		'unicorn/throw-new-error': 'error',
		'getter-return': 'error', // nursery
		'no-array-constructor': 'error', // ts recommended
		'no-case-declarations': 'error',
		'no-empty': 'error',
		'no-fallthrough': 'error',
		'no-negated-condition': 'error', // unicorn recommended
		'no-prototype-builtins': 'error',
		'no-redeclare': 'error',
		'no-regex-spaces': 'error',
		'no-unassigned-vars': 'off',
		'no-undef': 'off', // nursery
		'no-unexpected-multiline': 'error',
		'no-unreachable': 'error', // nursery
		'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_|stylex' }], // handles react/jsx-uses-vars
		'no-useless-constructor': 'off', // ts strict, not type-aware
		'preserve-caught-error': 'error',
		//
		'import/no-default-export': 'error',
		'react/exhaustive-deps': 'off',
		'react/jsx-filename-extension': ['error', { extensions: ['.jsx', '.tsx'] }],
		'no-console': 'warn',
	},
	overrides: [
		{
			files: ['**/*.{ts,tsx,mts,cts}'],
			plugins: ['typescript'],
			rules: {
				// recommended
				'typescript/ban-ts-comment': 'error',
				'typescript/no-empty-object-type': ['error', { allowInterfaces: 'with-single-extends' }],
				'typescript/no-explicit-any': 'off',
				'typescript/no-misused-promises': 'error',
				'typescript/no-namespace': 'error',
				'typescript/no-require-imports': 'error',
				'typescript/no-unnecessary-type-assertion': 'error',
				'typescript/no-unnecessary-type-constraint': 'error',
				'typescript/no-unsafe-argument': 'error',
				'typescript/no-unsafe-assignment': 'error',
				'typescript/no-unsafe-call': 'error',
				'typescript/no-unsafe-enum-comparison': 'error',
				'typescript/no-unsafe-function-type': 'error',
				'typescript/no-unsafe-member-access': 'error',
				'typescript/no-unsafe-return': 'error',
				'typescript/only-throw-error': 'error',
				'typescript/prefer-promise-reject-errors': 'error',
				'typescript/require-await': 'error',
				'typescript/restrict-plus-operands': 'error',
				// strict
				'typescript/no-confusing-void-expression': ['error', { ignoreArrowShorthand: true }],
				'typescript/no-deprecated': 'warn',
				'typescript/no-dynamic-delete': 'error',
				'typescript/no-extraneous-class': 'error',
				'typescript/no-invalid-void-type': 'error',
				'typescript/no-mixed-enums': 'error',
				'typescript/no-non-null-asserted-nullish-coalescing': 'error',
				'typescript/no-non-null-assertion': 'off',
				'typescript/no-unnecessary-boolean-literal-compare': 'error',
				'typescript/no-unnecessary-condition': 'error', // nursery
				'typescript/no-unnecessary-template-expression': 'error',
				'typescript/no-unnecessary-type-arguments': 'error',
				'typescript/no-unnecessary-type-conversion': 'off', // nursery, conflicts with react/jsx-no-leaked-render
				'typescript/no-unnecessary-type-parameters': 'error', // nursery
				'typescript/no-useless-default-assignment': 'error', // nursery
				'typescript/prefer-literal-enum-members': 'error',
				'typescript/prefer-reduce-type-parameter': 'error',
				'typescript/prefer-return-this-type': 'error',
				'typescript/related-getter-setter-pairs': 'error',
				'typescript/return-await': ['error', 'in-try-catch'],
				'typescript/unified-signatures': 'error',
				'typescript/use-unknown-in-catch-callback-variable': 'error',
				// https://github.com/typescript-eslint/typescript-eslint/blob/v8.56.1/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
				'constructor-super': 'off',
				'getter-return': 'off',
				'no-class-assign': 'off',
				'no-const-assign': 'off',
				'no-dupe-class-members': 'off',
				'no-dupe-keys': 'off',
				'no-func-assign': 'off',
				'no-import-assign': 'off',
				'no-new-native-nonconstructor': 'off',
				'no-obj-calls': 'off',
				'no-redeclare': 'off',
				'no-setter-return': 'off',
				'no-this-before-super': 'off',
				'no-undef': 'off',
				'no-unreachable': 'off',
				'no-unsafe-negation': 'off',
				'no-var': 'error',
				'no-with': 'off',
				'prefer-const': 'error',
				'prefer-rest-params': 'error',
				'prefer-spread': 'error',
			},
		},
		{
			files: ['**/*.{jsx,tsx}'],
			rules: {
				'unicorn/no-null': 'off',
			},
		},
	],
});
