on:
  workflow_call:

jobs:
  oxlint:
    name: oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          run-install: false
          cache: true
          cache-dependency-path: '**/package.json'
      - name: Install Dependencies
        # run: |
        #   if [ ${{ github.repository }} = "yjoer/camp" ]; then
        #     npm i --workspace @xcamp/config --include-workspace-root true
        #   else
        #     npm i --workspaces false --include-workspace-root true
        #   fi
        run: yarn install --no-immutable
      - name: Generate Types
        run: vp run -r gen-types
      - name: Oxlint
        run: vp lint
      - name: ESLint
        run: npx --no -- eslint --ext js,cjs,mjs,jsx,ts,tsx .
