on:
  workflow_call:

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: yarn
      - name: Install Dependencies
        run: yarn workspaces focus
      - name: Format
        run: npx --no -- prettier --ignore-path .gitignore --check "**/*.{css,scss,html,json,jsonc,md,mdx,xml,fxml,yml,yaml}" yarn.lock

  tombi:
    name: tombi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Tombi
        uses: tombi-toml/setup-tombi@cebfd308ba02edadfcee148b7473536990950c92
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: tombi lint
      - name: Format
        run: tombi format --check
