on:
  workflow_call:

jobs:
  # ruff-format:
  #   name: ruff format
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Ruff
  #       uses: astral-sh/ruff-action@v3
  #     - name: Format
  #       run: ruff format --check .

  ruff-check:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruff
        uses: astral-sh/ruff-action@v3
      - name: Lint
        run: ruff check .
