on:
  workflow_call:

jobs:
  # ruff-format:
  #   name: ruff format
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
  #     - name: Setup Ruff
  #       uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6
  #     - name: Format
  #       run: ruff format --check .

  ruff-check:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Ruff
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6
      - name: Lint
        run: ruff check .
