on:
  workflow_call:

jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint
          chmod +x ktlint
      - name: Format
        run: ./ktlint .
