name: Continuous Integration

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-commit-msg:
    uses: ./.github/workflows/verify-commit-msg.yml

  verify-js:
    uses: ./.github/workflows/verify-js.yml

  verify-py:
    uses: ./.github/workflows/verify-py.yml

  verify-rs:
    uses: ./.github/workflows/verify-rs.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      KERAS_BACKEND: torch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Rust
        run: rustup install 1.81.0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Environment Variables
        run: cp .env.example .env
      - name: Install Pango
        run: sudo apt-get update && sudo apt-get install libpango1.0-dev
      - name: Install Dependencies
        run: uv sync --extra torch --extra vision
      - name: Test
        run: uv run pytest
