name: Continuous Integration

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Check Formatting
        run: ruff format --check .
      - name: Check Import Ordering
        run: ruff check --select I .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint
        run: ruff check .

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      KERAS_BACKEND: torch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup Rust
        run: rustup install 1.81.0
      - name: Setup Rye
        uses: eifinger/setup-rye@v4
      - name: Setup Environment Variables
        run: cp .env.example .env
      - name: Install Pango
        run: sudo apt-get install libpango1.0-dev
      - name: Install Dependencies
        run: rye --env-file .env sync --features torch,vision
      - name: Test
        run: rye run pytest
