name: Publish Chromatic

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        type: choice
        options:
          - stories

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: '**/package.json'
      - name: Install Dependencies
        run: |
          PACKAGE_NAME=$(jq -r ".name" ${{ github.event.inputs.package }}/package.json)
          YARN_NM_HOISTING_LIMITS=workspaces yarn workspace $PACKAGE_NAME install --no-immutable
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ${{ github.event.inputs.package }}
          buildScriptName: build
