name: publish_npm

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        type: choice
        options:
          - packages/config
          - packages/webpack

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ github.event.inputs.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: |
          ROOT_PACKAGE_NAME=$(jq -r ".name" "${{ github.workspace }}/package.json")
          PACKAGE_NAME=$(jq -r ".name" package.json)
          pnpm install --frozen-lockfile --filter "${ROOT_PACKAGE_NAME}..." --filter "${PACKAGE_NAME}..."
      - name: Build Project Artifacts
        run: pnpm run build
      - name: Publish
        run: pnpm stage publish --access public --no-git-checks --provenance
