name: Publish Vercel

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        type: choice
        options:
          - examples/tanstack/start
          - examples/tanstack/start-solid
          - stories

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.package }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    environment: ${{ github.event.inputs.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: '**/package.json'
      - name: Setup Mise
        uses: jdx/mise-action@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install Dependencies
        run: |
          PACKAGE_NAME=$(jq -r ".name" package.json)
          YARN_NM_HOISTING_LIMITS=workspaces yarn workspace $PACKAGE_NAME install --no-immutable
      - name: Build Project Artifacts
        run: mise run build:vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
