name: Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        type: choice
        options:
          - packages/webpack

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g pnpm@latest-10
      - run: |
          pnpm config set recursive-install false
          pnpm i
        working-directory: ${{ github.event.inputs.package }}
      - run: npx jsr publish
        working-directory: ${{ github.event.inputs.package }}
