name: Publish Vercel

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        type: choice
        options:
          - examples/tanstack/start
          - examples/tanstack/start-solid
          - stories

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    environment: ${{ github.event.inputs.package }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754
        with:
          node-version: 24
          run-install: false
          cache: true
      - name: Setup Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install Dependencies
        working-directory: ${{ github.event.inputs.package }}
        run: |
          ROOT_PACKAGE_NAME=$(jq -r ".name" "${{ github.workspace }}/package.json")
          PACKAGE_NAME=$(jq -r ".name" package.json)
          yarn workspaces focus $ROOT_PACKAGE_NAME $PACKAGE_NAME
      - name: Build Project Artifacts
        working-directory: ${{ github.event.inputs.package }}
        run: mise run build:vercel
      - name: Deploy Project Artifacts to Vercel
        working-directory: ${{ github.event.inputs.package }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
